language: csharp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5
  - sudo apt-get install -y make g++
  - sudo apt-get install -y npm
  - sudo add-apt-repository ppa:chris-lea/node.js -y
  - sudo apt-get update -qq
  - sudo apt-get install -y nodejs
  - whereis node
  - sudo ln -s /usr/bin/node /usr/bin/nodejs
  - sudo npm config set spin=false
  - sudo npm update -g npm

install:
  - node -v
  - npm -v
  - whereis node
  - whereis npm
  - npm install
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux update-propel

script:
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev start-testrunner