language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - DB=mysql

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update -qq
  - sudo apt-get install -y mono-complete
  - sudo apt-get install -y make g++
  - sudo apt-get install -y npm
  - sudo add-apt-repository ppa:chris-lea/node.js -y
  - sudo apt-get update -qq
  - sudo apt-get install -y nodejs
  - sudo npm config set spin=false
  - sudo npm update -g npm
  - node -v
  - npm -v
  - mysql -e 'create database ecp;'

install:
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=travis setup-dev
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=travis update-db
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=travis update-propel

script:
  - export CHROME_BIN=chromium-browser
  - export FIREFOX_BIN=firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=travis start-testrunner-once