language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update -qq
  - sudo apt-get install -y mono-complete
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y npm
  - sudo ln -s /usr/bin/nodejs /usr/bin/node

install:
  - node --version
  - whereis npm
  - sudo npm install -g graceful-fs
  - npm update
  - /usr/share/npm/npm install
  - /usr/bin/X11/npm install
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux update-propel

script:
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev start-testrunner