language: csharp

before_install:
  - sudo apt-get install -y php
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y npm
  - sudo ln -s /usr/bin/node /usr/bin/nodejs

install:
  - node --version
  - whereis npm
  - sudo npm install -g graceful-fs
  - npm update
  - /usr/share/npm/npm install
  - /usr/bin/X11/npm install
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux update-propel

script:
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev start-testrunner