language: php
php:
  - nightly

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update -qq
  - sudo apt-get install -y mono-complete
  - sudo apt-get install -y make g++
  - sudo apt-get install -y npm
  - sudo add-apt-repository ppa:chris-lea/node.js -y
  - sudo apt-get update -qq
  - sudo apt-get install -y nodejs
  - sudo npm config set spin=false
  - sudo npm update -g npm
  - whereis composer
  - sudo curl -sS https://getcomposer.org/installer| php
  - sudo mv composer.phar /usr/bin/composer

install:
  - node -v
  - npm -v
  - whereis node
  - whereis npm
  - cd /public/rest
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev
  ls -Al /public/rest/vendor/propel/propel 
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux update-propel

script:
  - mono "lib/nant/bin/NAnt.exe" -buildfile:build/build.build -D:system=linux setup-dev start-testrunner